### ISSUE TITLE
New pcntl requirement could break PHP-FPM

### ISSUE THREAD

**Issue by Dando-Real-ITA** [amphp/concurrent#156]
As pointed in this issue https://github.com/amphp/process/issues/64 pcntl is not available in FPM
I will try to update to latest commits and test in FPM but meanwhile I wanted to point this out, thanks.

**Comment by trowski** [comment]
`ext-pcntl` is not a requirement, but an optional dependency. I am curious about FPM compatibility, so please open a new issue if you run into any issues. 👍
