### ISSUE TITLE
Is there a way to output the STDOUT of the child process to STDOUT of the parent process?

### ISSUE THREAD

**Issue by santossoares** [amphp/concurrent#176]
I have a task that i need to output to the parent process.
Is there a way to make the echo print on the console?

```php
class FetchTask implements Task
{
    public function run(Channel $channel, Cancellation $cancellation): string
    {
        for ($i = 0; $i < 10; $i++) {
	sleep(1);
	echo $1;
	}
        return 'end';
    }
}
```

**Comment by trowski** [comment]
There a couple of ways this could be accomplished.

---

You can pipe the stdout/stderr of the process used for the worker context to the stdout/stderr of the parent. To do this, you will need to implement a `ContextFactory` which puts this piping in place.

```php
use Amp\ByteStream;
use Amp\Cancellation;
use Amp\Parallel\Context\ContextFactory;
use Amp\Parallel\Context\ProcessContextFactory;
use function Amp\async;

class StdIoForwardingProcessContextFactory implements ContextFactory
{
    public function __construct(
        private readonly ProcessContextFactory $contextFactory = new ProcessContextFactory(),
    ) {
    }

    public function start(array|string $script, ?Cancellation $cancellation = null): Context
    {
        $process = $this->contextFactory->start($script, $cancellation);

        async(ByteStream\pipe(...), $process->getStdout(), ByteStream\getStdout())->ignore();
        async(ByteStream\pipe(...), $process->getStderr(), ByteStream\getStderr())->ignore();

        return $process;
    }
}
```

This `ContextFactory` can then be provided to the constructor of `ContextWorkerFactory`, in turn can be provided to the constructor of `ContextWorkerPool`.

```php
$factory = new ContextWorkerFactory(contextFactory: new StdIoForwardingProcessContextFactory);
$pool = new ContextWorkerPool(factory: $factory);
```

---

Another option would be to use the `Channel` instance provided to the `Task` to send the information you want back to the parent, then loop on the channel sending data to stdout in the parent. The example here uses `null` as a marker to indicate output from the task is ending.

```php
$execution = $pool->submit($task);

while ($data = $channel->receive()) {
    echo $data;
}
```

If you were already using the channel for another purpose, consider sending lightweight objects on the channel with a type enum. This strategy is used is [`amphp/cluster`](https://github.com/amphp/cluster) for sending messages between the cluster watcher and cluster workers: [receiving IPC messages in cluster](https://github.com/amphp/cluster/blob/532bfd25d1e434e9826ca0891d6519e4602075ad/src/Internal/Worker.php#L69-L84)

**Comment by santossoares** [comment]
I thought about using the channel to communicate between processes, but I couldn't find any examples of how to use it.

I didn't understand your example above.

```php
class FetchTask implements Task
{
    public function run(Channel $channel, Cancellation $cancellation): string
    {
        for ($i = 0; $i < 10; $i++) {
	    sleep(1);
	
	    $channel->send('hello');
	}
        return 'end';
    }
}


```
Is that correct on the task?

But how to get that data ('hello') on the parent?

```php
$worker = Amp\Parallel\Worker\createWorker();
$task = new FetchTask();

$execution = $worker->submit($task);

// $data will be the return value from FetchTask::run()
$data = $execution->await();

// how to get the $channel to work?
while ($channelData = $channel->receive()) {
    echo $channelData;
}

```

**Comment by trowski** [comment]
You're very close, but are missing a couple things and need to do some reordering of operations to await in the parent when appropriate.

```php
class FetchTask implements Task
{
    public function run(Channel $channel, Cancellation $cancellation): string
    {
        for ($i = 0; $i < 10; $i++) {
	    sleep(1);
	
	    $channel->send('hello');
	    $channel->send(null); // Send null to signal the channel will not send more data
	}

        return 'end';
    }
}
```

```php
$worker = Amp\Parallel\Worker\createWorker();
$task = new FetchTask();

$execution = $worker->submit($task);

// The loop receiving data must come before await()
while ($channelData = $channel->receive()) {
    echo $channelData;
}

// Execution stops at Execution::await() until the task completes
$data = $execution->await();
```

Ordering of operations in the parent should mirror that of the task. If the task sends data over the channel, the parent must receive that data before awaiting the return value of the task.

You can use separate coroutines (fibers) to await the result without blocking the main code flow. The example below is somewhat contrived, but hopefully gives you an idea of what is possible. See https://amphp.org/architecture for more on coroutines and futures.

```php
$worker = Amp\Parallel\Worker\createWorker();
$task = new FetchTask();

$execution = $worker->submit($task);

// Awaiting in another coroutine prevents blocking {main}
$future = Amp\async(function () use ($execution): void {
    $result = $execution->await();
    echo "Received '{$result}' from task\n";
});

while ($channelData = $channel->receive()) {
    echo $channelData;
}
```

**Comment by santossoares** [comment]
Tks for the feedback!
