### ISSUE TITLE
Performance degradation in v2.2.0

### ISSUE THREAD

**Issue by PNixx** [amphp/concurrent#179]
<img width="419" alt="Снимок экрана 2023-05-18 в 21 27 59" src="https://github.com/amphp/parallel/assets/1117351/9c25ddb9-b85d-4164-8204-74c66eb6eee7">

The red line at the bottom of the graph shows when the worker was launched and processed tasks. In version 2.2.0, a few seconds after the start, the tasks stop being processed, and there are no messages in the logs. When you return to version 2.1.0, everything starts working properly.

**Comment by trowski** [comment]
I assume this is due to 37850ff591155c6f5c662173c3fc75682752c918, which fixed potentially assigning two tasks to a single worker. Are your tasks executing asynchronously? If so, I could see this resulting in lower throughput. I'm not able to replicate tasks not being processed. Any other insights you could give me?

**Comment by PNixx** [comment]
> Are your tasks executing asynchronously?

yes.

I am using [amp/http-client](https://github.com/amphp/http-client) and [amp/file](https://github.com/amphp/file) libraries to download photos.

**Comment by kelunik** [comment]
Any reason why you're using amphp/parallel then at all instead of using them in the main process?

**Comment by PNixx** [comment]
I think library amphp/file using amphp/parallel.

**Comment by kelunik** [comment]
Ah, so you only use it indirectly for file accesses?

**Comment by PNixx** [comment]
Yes, for write, delete file and etc.

**Comment by trowski** [comment]
Please update to `v2.2.1` and let me know if you still experience the same issues.

**Comment by PNixx** [comment]
It only got worse. Processing stops almost instantly.

**Comment by kelunik** [comment]
@PNixx Do you have a custom worker limit?

**Comment by PNixx** [comment]
50 tasks pool limit in only RabbitMQ consumer

**Comment by PNixx** [comment]
Now it works correctly. Maybe related dependencies have been updated, maybe revolt library fixed it.

**Comment by PNixx** [comment]
<img width="452" alt="Снимок экрана 2023-11-21 в 10 25 19" src="https://github.com/amphp/parallel/assets/1117351/fc91978e-bd07-44fc-ad4d-f194079036cb">

The problem is still recurring.
revolt/event-loop v1.0.5

**Comment by PNixx** [comment]
Example code:

`process.php`:

```php
use Amp\Sync\Channel;
use Pictures\ImageMagicProcessor;
return function (Channel $channel): int {
	/** @var ImageMagicProcessor $processor */
	$processor = $channel->receive();
	$processor->process();
	return true;
};
```

`ImageMagicProcessor.php`:

```php
namespace Pictures;

use Amp\Cancellation;
use Amp\ByteStream;
use Core\Logger;
use function Amp\async;

class ImageMagicProcessor {

	/**
	 * @param string     $path
	 * @param int|string $width
	 * @param int        $sharpen
	 * @param string     $destination
	 */
	public function __construct(protected readonly string $path, protected readonly int|string $width, protected readonly int $sharpen, protected readonly string $destination) {}

	/**
	 * @throws \Throwable
	 */
	public function async(?Cancellation $cancellation): void {
		// Create a new child process that does some blocking stuff.
		$context = \Amp\Parallel\Context\contextFactory()->start(APP_ROOT . "/bin/process.php");

		// Pipe any data written to the STDOUT in the child process to STDOUT of this process.
		async(fn() => ByteStream\pipe($context->getStdout(), Logger::$writable, $cancellation));
		async(fn() => ByteStream\pipe($context->getStderr(), Logger::$writable, $cancellation));

		// Data sent to child process, received on line 9 of blocking-process.php
		$context->send($this);

		// Wait
		$context->join($cancellation);
	}

	/**
	 * @throws \ImagickException
	 */
	public function process(): void {
		$dir = pathinfo($this->destination, PATHINFO_DIRNAME);

		$imagick = new \Imagick(realpath($this->path));
		try {
			$imagick->scaleImage($this->width, $this->width, true);
			$imagick->sharpenImage(0, $this->sharpen);
			$imagick->autoLevelImage();
			$imagick->setImageBackgroundColor('white');
			$imagick->setImageAlphaChannel(\Imagick::ALPHACHANNEL_REMOVE);
			$imagick->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);
			$imagick->writeImage($this->destination);
		} finally {
			$imagick->destroy();
		}
	}
}
```

How use it:
```php
(new ImageMagicProcessor($params['path'], $params['width'], $params['sharpen'] ?? 1, $destination))->async(new TimeoutCancellation(30));
```

**Comment by kynx** [comment]
Apologies if I'm being dumb here - I'm very new to amphp - but...
```php
return function (Channel $channel): int {
	/** @var ImageMagicProcessor $processor */
	$processor = $channel->receive();
	$processor->process();
	return true;
};
```
Won't you get an error returning `true`, when the function says it returns an `int`?

**Comment by PNixx** [comment]
Not, it work correctly

**Comment by PNixx** [comment]
Same problem in the new version `v2.2.4`. PHP 8.1.26.

**Comment by trowski** [comment]
```php
// Pipe any data written to the STDOUT in the child process to STDOUT of this process.
async(fn() => ByteStream\pipe($context->getStdout(), Logger::$writable, $cancellation));
async(fn() => ByteStream\pipe($context->getStderr(), Logger::$writable, $cancellation));
```

This code is conflicting with piping of STDOUT and STDERR in `DefaultContextFactory`, causing the child process to immediately crash. Either remove this, or use `ProcessContextFactory` instead.

Also note that your code would be much more performant if you used a `Task` implementation for image processing and used the worker API. That way worker processes would be reused for multiple tasks instead of spinning up a new process for every image.

**Comment by PNixx** [comment]
Thanks, `Task` implementation resolved this problem.
