### ISSUE TITLE
Parallel task(s) keep on running since v2.2

### ISSUE THREAD

**Issue by veewee** [amphp/concurrent#180]
Hello,

Since parallel v2.2 - the parallel tasks in `grumphp` keep on running on CI:
https://github.com/phpro/grumphp/actions/runs/4831876707/jobs/9024673371

I am not able to consistently reproduce this on my local machine - but CI does consistently keep on hanging.
The times that I can reproduce, It looks like 1 tasks is not being completed anymore for some reason.

As you can see, the github actions with amp v2.1 (prefer-lowest dependencies) work as expected.

Any clue what could go wrong in this new version of amphp/parallel? 

FYI, grumphp's parallel implementation can be found in these 3 filed:

* https://github.com/phpro/grumphp/blob/v2.x/src/Runner/Middleware/HandleRunnerMiddleware.php - awaits alll tasks to be done
* https://github.com/phpro/grumphp/blob/v2.x/src/Runner/Parallel/SerializedClosureTask.php - the parallel task
* https://github.com/phpro/grumphp/blob/v2.x/src/Runner/TaskHandler/Middleware/ParallelProcessingMiddleware.php - the configuration that submits  a single execution of a parallel task

**Comment by trowski** [comment]
I assume this is due to 37850ff591155c6f5c662173c3fc75682752c918, which was also reported in #179 with tasks hanging. I'm not seeing why this might be happening, and the tests aren't revealing the issue either.

**Comment by trowski** [comment]
Please update to `v2.2.1` and let me know if this fixes your issues.

**Comment by veewee** [comment]
Yes, that works. Thanks for fixing! :)
