### ISSUE TITLE
Sock files are piling up in tmp folder. They are not getting cleared up automatically.

### ISSUE THREAD

**Issue by MindGamer7** [amphp/concurrent#183]
I am using simple code similar to as follow as shown in AMPHP parallel example. However, sock files in tmp folder keep piling up
`$executions = [];
foreach ($urls as $url) {
    // FetchTask is just an example, you'll have to implement
    // the Task interface for your task.
    $executions[$url] = Worker\submit(new FetchTask($url));
}

// Each submission returns an Execution instance to allow two-way
// communication with a task. Here we're only interested in the
// task result, so we use the Future from Execution::getFuture()
$responses = Future\await(array_map(
    fn (Worker\Execution $e) => $e->getFuture(),
    $executions,
));

class FetchTask implements Task
{
    public function __construct(
        private readonly string $url,
    ) {
    }

    public function run(Channel $channel, Cancellation $cancellation): string
    {
        return file_get_contents($this->url); // Example blocking function
    }
}
`
The code runs fine but sock files are not cleared in system tmp folder. Please any suggestion what need to be done?

**Comment by trowski** [comment]
Thanks for pointing out this issue! The temporary file was removed if the IPC socket was explicitly closed, but was not removed if the IPC socket was closed through destruction.

**Comment by medy36** [comment]
Hello @trowski, i had encountered the issue of .socket files left in server /tmp/ folder, which was successfully resolved after your fix in >2.2.4.

Today after deploying an ASYNC work doing the same parallel work, I have found that the sockets are again still left in the /tmp/ folder.

I am using 2.2.9 parallel, the sync method is freeing the /tmp/ from socket but the Async does leave the .socket files.
