### ISSUE TITLE
Queue-based pool

### ISSUE THREAD

**Issue by hitriyvalenok** [amphp/concurrent#197]
Hello! I'm using a pool of tasks. Any time I may need to stop them all. For it, I'm using ContextWorkerPool. My issue is that `submit` runs the worker and waits for task completion if the `$limit` is over. Thus, I cannot control execution since I should wait until all tasks over limits are completed. I think it would be a good solution if there was a kinda the queue-based pool where I could add all my tasks, run execution, and wait asynchronously. How I can solve my task? I am not sure I'm doing it with the most graceful method. Thank you.

**Comment by kelunik** [comment]
What do you mean with wait asynchronously?

**Comment by hitriyvalenok** [comment]
I mean I don't want that `submit` force me to wait for the task completion. I'd prefer to use `wait` for it.

**Comment by kelunik** [comment]
Which version of parallel do you use?

**Comment by hitriyvalenok** [comment]
2.2

**Comment by hitriyvalenok** [comment]
Right now I'm trying to stop the task by throwing an exception from the `run` method. I want to throw an exception from `submit` - thanks to it I can catch it without any waits. But I found that only `die` throws something (`ChannelException`) from `submit`; any other exceptions can be caught only in the `wait` methods.

Ideally, I would start all tasks asynchronously, then call `ContextWorkerPool->shutdown()`, but `submit` is spoiling the whole raspberries. Also, it's ok for me to throw something like `CancelledException` and catch it in `submit`.

**Comment by trowski** [comment]
If you want to limit the number of tasks being submitted to the pool, consider using some of our abstractions for queues, mutexes/semaphores, or concurrency. You can find these in [`amphp/sync`](https://github.com/amphp/sync) and [`amphp/pipeline`](https://github.com/amphp/pipeline).

For example, you may be able to use a `Pipeline` to limit the concurrency.

```php
Pipeline::fromIterable($taskIterable) // $taskIterable is an iterable producing Task objects.
    ->concurrent(10) // Limit to 10 simultaneous tasks
    ->map(fn (Task $task) => workerPool()->submit($task))
    ->map(fn (Execution $execution) => $execution->await())
    ->forEach(function ($result): void {
        // Do something with task result in $result.
    });
```

**Comment by hitriyvalenok** [comment]
Thanks, it works! However, I was faced with unusual behavior. If I set the concurrent value to 1 or 2, it starts 2 threads simultaneously. With 3+ it works as expected.

**main.php**
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Amp\Parallel\Worker\Execution;
use Amp\Parallel\Worker\Task;
use Amp\Pipeline\Pipeline;
use Bro\SampleTask;
use function Amp\Parallel\Worker\workerPool;

$task = new SampleTask();
Pipeline::fromIterable( [ $task, $task, $task, $task ] )
        ->concurrent( 1 )
        ->map( fn( Task $task ) => workerPool()->submit( $task ) )
        ->map( fn( Execution $execution ) => $execution->await() )
        ->forEach( function( $result ): void {
        } )
;
```

**SampleTask.php**
```php
<?php
namespace Bro;

use Amp\Cancellation;
use Amp\Parallel\Worker\Task;
use Amp\Sync\Channel;
use DateTime;

class SampleTask implements Task
{
    public function run( Channel $channel, Cancellation $cancellation ): mixed
    {
        sleep( 2 );

        $now = DateTime::createFromFormat( 'U.u', sprintf( '%.6F', microtime( true ) ) )->format( 'H-i-s.u' );
        file_put_contents( __DIR__ . '/../test.log', "$now\n", FILE_APPEND ); // logging the current time. With the concurrent value 1 or 2, you'll see 2 records with almost the same time

        return true;
    }
}
```

**Comment by hitriyvalenok** [comment]
Thanks! But it for some reason starts x2 threads. For example, in this code tasks started two each, although the concurrent value is set to 1. With concurrent=2 4 simultaneous tasks will be started.
```php
use Amp\Parallel\Worker\Execution;
use Amp\Parallel\Worker\Task;
use Amp\Pipeline\Pipeline;
use Bro\SampleTask;
use function Amp\Parallel\Worker\createWorker;

class SampleTask implements Task
{
    public function run( Channel $channel, Cancellation $cancellation ): mixed
    {
        sleep( 2 );
        return true;
    }
}

$tasksToStart = 4;
$concurrent = 1;
$task = new SampleTask();

$tasks = [];
for( $taskNum = 0; $taskNum < $tasksToStart; ++$taskNum ) {
    $tasks[] = $task;
}

Pipeline::fromIterable( $tasks )
        ->concurrent( $concurrent )
        ->map( fn( Task $task ) => createWorker()->submit( $task ) ) // no pools
        ->map( fn( Execution $execution ) => $execution->await() )
        ->forEach( function( $result ): void {
            $currentTime = DateTime::createFromFormat( 'U.u', sprintf( '%.6F', microtime( true ) ) )->format(
                'H-i-s.u'
            );
            echo "$currentTime\n";
        } )
;
```

Output:
```
19-34-27.059025
19-34-27.121341
19-34-29.123185
19-34-29.181591
```

**Comment by trowski** [comment]
Multiple tasks are being executed because you're creating the tasks before awaiting the tasks to be completed. Awaiting is what will apply back-pressure to the pipeline (or rather the underlying concurrent iterator) and cause it to wait to consume more values from the source iterator.

Changing the example to create an then await the task in the same function will only executed the expected number of tasks at once.

```php

Pipeline::fromIterable( $tasks )
        ->concurrent( $concurrent )
        ->map( fn( Task $task ) => createWorker()->submit( $task )->await() ) // submit and await task to complete
        ->forEach( function( $result ): void {
            $currentTime = DateTime::createFromFormat( 'U.u', sprintf( '%.6F', microtime( true ) ) )->format(
                'H-i-s.u'
            );
            echo "$currentTime\n";
        } )
;
```
