### ISSUE TITLE
Despite of DeferredCancellation::cancel() call Cancellation::isRequested() is always false in tasks submitted to ContextWorkerPool

### ISSUE THREAD

**Issue by hitriyvalenok** [amphp/concurrent#198]
Hello! In the sample I call `cancel()` and pass the `DeferredCancellation` instance to the `submit`, but the `Cancellation` in a task always stays unrequested.

main.php:
```php 
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Amp\DeferredCancellation;
use Amp\Parallel\Worker\ContextWorkerPool;
use Bro\SampleTask;

$cancellation = new DeferredCancellation();
$cancellation->cancel();

$pool = new ContextWorkerPool( 1 );
$exec = $pool->submit( new SampleTask, $cancellation->getCancellation() );
$exec->await();
```

SampleTask.php:
```php
<?php
namespace Bro;

use Amp\Cancellation;
use Amp\Parallel\Worker\Task;
use Amp\Sync\Channel;

class SampleTask implements Task
{
    public function run( Channel $channel, Cancellation $cancellation ): mixed
    {
        file_put_contents( __DIR__ . '/isRequested.log', ( $cancellation->isRequested() ) ? 'true' : 'false' ); // always false :(
        return true;
    }
}
```

If it is my failure, what I'm doing wrong? Thanks!

**Comment by hitriyvalenok** [comment]
I'm researching ContextWorkerPool.php. For some reason property `$deferredCancellation` that passed in `workerFactory()->create()` is private. But it uses nowhere. It looks like an author planned to share it or use it internally, but forgot about it :)

**Comment by trowski** [comment]
Hi @hitriyvalenok!

The issue is that a task cancellation is sent as a separate message to the worker after the task has started. Since your sample task executes and completes immediately, there is no opportunity for the worker to receive the message that the task has been cancelled.

We're considering not submitting cancelled tasks at all to the worker, as this of course would save overhead if a task has already been cancelled before a worker becomes available.

**Comment by hitriyvalenok** [comment]
Thank you! Honestly, it was just a test in part of my studying. I don't think you needed to add any commits about my case... I agree it is a bad idea generally. Now I understand my mistake clearly.

May I ask one more question? I need to cancel all the tasks from any task. Those, I need to send from a task a cancellation signal to all other tasks. I would like to do it by calling cancel(), but I haven't a DeferredCancellation instance inside the task. I suppose I need to use a callback here, but how to pass it to the task?

**Comment by trowski** [comment]
> I need to cancel all the tasks from any task.

I'm not entirely sure what you mean. Tasks are independent and unable to communicate with other tasks. Your parent process may keep a list of tasks and cancel them when needed. Alteratively, you may pass the same cancellation from a single `DeferredCancellation` to multiple calls to `Worker::submit()`. Requesting cancellation of that deferred cancellation will cancel all tasks which received the contained cancellation.
