### ISSUE TITLE
Reporting Warning in amphp/parallel Usage on Windows System

### ISSUE THREAD

**Issue by directsoftware** [amphp/concurrent#200]
Hello,

I am writing to report a warning that occurs while utilizing your library on the Windows operating system. For context, I am currently using Windows 11.

The warning message is as follows:
`PHP Warning: cli_set_process_title(): cli_set_process_title had an error: Windows error code: 6 in /path/to/project/vendor/amphp/parallel/src/Context/Internal/process-runner.php on line 16`

**Comment by trowski** [comment]
[This line](https://github.com/amphp/parallel/blob/051211ab318781b95926c7068db22f9810270779/src/Context/Internal/process-runner.php#L16) was using the error suppression operator (`@`), so this warning should not have been issued. You likely are using an error handler which does not respect the current error reporting level.

This mistake is frequently made, so as we've been converting uses of `@` to explicitly set the error handler instead, which I've done to avoid this in the future.
