### ISSUE TITLE
Reopen Issue: Zombie .sock Files Not Being Deleted in CLI Mode

### ISSUE THREAD

**Issue by medy36** [amphp/concurrent#202]
Hi team,

I would like to reopen the issue regarding the zombie .sock files not being correctly deleted when using amphp/parallel.

**Background:**
I am running parallel tasks using amphp/parallel in two different environments:

-     Web

-     CLI (via a cron job)

After a recent update to the amphp/parallel library, I noticed an improvement where the .sock files were correctly deleted in the web version. However, the CLI version still leaves .sock files in the /tmp folder, which eventually leads to issues.

**Steps to Reproduce:**

-     Run parallel tasks using amphp/parallel in a web environment.

-     Observe that .sock files are deleted correctly.

-     Run the same parallel tasks in a CLI environment (e.g., via a cron job).

-     Observe that .sock files are not deleted and accumulate in the /tmp folder.

I suspect that the issue might be related to the way "LocalIpcHub"  handles cleanup operations differently in web and CLI environments. Any insights or suggestions on how to resolve this issue for the CLI environment would be greatly appreciated.

**Comment by peteroxil** [comment]
I've had a hard to trace zombie sock problem - I hadn't noticed the connection with running via CLI - good spot!

**Comment by medy36** [comment]
Hi @trowski, would be very helpful if you can have a look at this case please. thank you

**Comment by medy36** [comment]
Helle @kelunik, Can you have a look at this issue please?

**Comment by medy36** [comment]
i am going to reopen the subject with more details about the situation.
