### ISSUE TITLE
Not working inside a PHAR

### ISSUE THREAD

**Issue by theofidry** [amphp/concurrent#48]
After debugging this for a while I couldn't find any solution or pinpoint the real issue so attempting it here...

Basically for [Box](https://github.com/humbug/box), when you rename it's PHAR from `box.phar` to `box`, i.e. renaming it to a name without the `.phar` extension, it stops being usable with Amp Parallel.

Indeed when Amp spawns Workers, it seems to be requiring the Composer Autoloader but that's it. In the case of Box as it needs more in the spawners, I'm [registering a bootstrap closure](https://github.com/humbug/box/blob/master/src/bootstrap.php#L57) which [I call in the worker](https://github.com/humbug/box/blob/master/src/Box.php#L317-L344).

Now there is two issues when the PHAR is renamed to `box`:

- It cannot find the Composer autoloader => actually it's not an issue as Amp already does it, so even if it did it would end up in a fatal error because trying to declare again the Composer classes. So the fix here is to remove it as done in https://github.com/humbug/box/pull/160/files
- It cannot find the other function class `vendor/humbug/php-scoper/src/functions.php`

That's where I'm not sure what Amp does with the temporary files to try to execute the Workers when it's inside a PHAR. But it seems this part is _not_ execute from inside the PHAR so I can't use the `phar://box-alias.phar/vendor/humbug/php-scoper/src/functions.php` to point to `functions.php` (the Box PHAR does not have an alias yet but I tried with it).

Any idea?

**Comment by kelunik** [comment]
PHARs and multiple processes are really tricky, see https://github.com/amphp/parallel/commit/732694688461936bec02c0ccf020dfee10c4f7ee for what we do to work around the quirks. As soon as the PHAR doesn't have a `.phar` extension, PHP won't recognize it as PHAR anymore.

The real fix will be fixing PHP itself, so it can work with PHARs regardless of the name, e.g. with a format like `phar://phar/to/box#!vendor/...`.

**Comment by theofidry** [comment]
I'll give it a go. Is there any reason to use a copy instead of a symlink?

**Comment by kelunik** [comment]
I'm not sure whether there's a reason. The commit message says symlink, so maybe I changed it to a copy after testing, but don't really remember.

The function needs to be static, so it doesn't old a reference to `$this`.
